on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.9", "3.10", "3.11"]
    container:
      image: python:${{ matrix.python }}-alpine
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install git
        run: apk upgrade && apk add git
      - name: pre-commit
        run: python -m venv ~/.pre-commit && ~/.pre-commit/bin/pip install --upgrade pip && ~/.pre-commit/bin/pip install pre-commit && ~/.pre-commit/bin/pre-commit run --all
      - name: install poetry
        run: python -m venv ~/.poetry && ~/.poetry/bin/pip install --upgrade pip && ~/.poetry/bin/pip install poetry
      - name: install python dependencies
        run: ~/.poetry/bin/poetry install
      - name: allow access to the virtualenv
        run: echo PATH="$(~/.poetry/bin/poetry run printenv VIRTUAL_ENV)/bin:${PATH}" >> $GITHUB_ENV
      - name: pytest
        run: pytest --cov=ragdoll --cov-report term-missing tests/
      - name: build
        run: ~/.poetry/bin/poetry build
